name: nomofomo action

on:
  schedule:
    - cron: '*/10 * * * *'

permissions:
  contents: read

jobs:
  nomofomo_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run nomofomo
      run: python main.py
      env:
        CM_URL: ${{ secrets.CM_URL }}
        HB_URL: ${{ secrets.HB_URL }}
        TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER }}
        MY_NUMBER: ${{ secrets.MY_NUMBER }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
